language: node_js

node_js:
- '0.11'

notifications:
  email:
    recipients:
      - ryojiosawa@gmail.com
      - allenkrulwich@gmail.com
      - carlgoldberg1236@gmail.com
      - supriya.bhat@gmail.com
    on_success:
      - always|never|change
    on_failure:
      - always|never|change
